### ISSUE TITLE
Error running `./bin/js`

### ISSUE THREAD

**Issue by Fishrock123** [js-js/js.js#25]
OS X 10.10 if It matters. Dunno what this means lol.

0.10.32

```
dyld: Symbol not found: _node_module_register
  Referenced from: /Users/Jeremiah/Documents/js.js/node_modules/weak/build/Release/weakref.node
  Expected in: dynamic lookup
```

0.11.14

```
/Users/Jeremiah/Documents/js.js/node_modules/jit.js/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/Users/Jeremiah/Documents/js.js/node_modules/jit.js/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/Jeremiah/Documents/js.js/node_modules/jit.js/lib/jit.js:4:34)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

**Comment by Fishrock123** [comment]
this is what I get for partial installing using 0.11.14 >_<
